USE Library;
GO

IF NOT EXISTS (SELECT 1 FROM EmailTemplates WHERE Purpose = 'Issue Request')
INSERT INTO EmailTemplates (Purpose, Subject, Body) VALUES ('Issue Request', 'Issue Request Received: {{BookName}}', '');

UPDATE EmailTemplates SET Body = '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; box-shadow: 0 10px 25px rgba(0,0,0,0.05);"><div style="background-color: #0F172A; padding: 25px 20px; text-align: center; border-bottom: 4px solid #ea580c;"><h2 style="color: #ffffff; margin: 0; font-size: 22px; letter-spacing: 1px;">JINDAL STAINLESS</h2><p style="color: #ea580c; font-size: 11px; margin: 5px 0 0 0; text-transform: uppercase; letter-spacing: 2px; font-weight: bold;">Corporate Library Portal</p></div><div style="padding: 35px 30px; background-color: #ffffff; color: #334155; line-height: 1.7;"><h3 style="color: #0F172A; margin-top: 0; font-size: 18px;">Request Received</h3><p>Hello,</p><p>We have received your request to issue the book <strong style="color: #ea580c;">''{{BookName}}''</strong>. You will be notified once it is approved by the administration.</p><p style="margin-top: 30px;">Best Regards,<br><strong style="color: #0F172A;">Library Admin</strong></p></div><div style="background-color: #f8fafc; padding: 15px; text-align: center; font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0;">&copy; 2026 Jindal Stainless Limited. All rights reserved.</div></div>'
WHERE Purpose = 'Issue Request';

IF NOT EXISTS (SELECT 1 FROM EmailTemplates WHERE Purpose = 'Request Approved')
INSERT INTO EmailTemplates (Purpose, Subject, Body) VALUES ('Request Approved', 'Issue Request Approved: {{BookName}}', '');

UPDATE EmailTemplates SET Body = '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; box-shadow: 0 10px 25px rgba(0,0,0,0.05);"><div style="background-color: #0F172A; padding: 25px 20px; text-align: center; border-bottom: 4px solid #ea580c;"><h2 style="color: #ffffff; margin: 0; font-size: 22px; letter-spacing: 1px;">JINDAL STAINLESS</h2><p style="color: #ea580c; font-size: 11px; margin: 5px 0 0 0; text-transform: uppercase; letter-spacing: 2px; font-weight: bold;">Corporate Library Portal</p></div><div style="padding: 35px 30px; background-color: #ffffff; color: #334155; line-height: 1.7;"><h3 style="color: #0F172A; margin-top: 0; font-size: 18px;">Request Approved</h3><p>Hello {{EmployeeName}},</p><p>Great news! Your request to issue the book <strong style="color: #ea580c;">''{{BookName}}''</strong> has been approved and issued to your account.</p><p style="margin-top: 30px;">Best Regards,<br><strong style="color: #0F172A;">Library Admin</strong></p></div><div style="background-color: #f8fafc; padding: 15px; text-align: center; font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0;">&copy; 2026 Jindal Stainless Limited. All rights reserved.</div></div>'
WHERE Purpose = 'Request Approved';

IF NOT EXISTS (SELECT 1 FROM EmailTemplates WHERE Purpose = 'Request Rejected')
INSERT INTO EmailTemplates (Purpose, Subject, Body) VALUES ('Request Rejected', 'Issue Request Rejected: {{BookName}}', '');

UPDATE EmailTemplates SET Body = '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; box-shadow: 0 10px 25px rgba(0,0,0,0.05);"><div style="background-color: #0F172A; padding: 25px 20px; text-align: center; border-bottom: 4px solid #ea580c;"><h2 style="color: #ffffff; margin: 0; font-size: 22px; letter-spacing: 1px;">JINDAL STAINLESS</h2><p style="color: #ea580c; font-size: 11px; margin: 5px 0 0 0; text-transform: uppercase; letter-spacing: 2px; font-weight: bold;">Corporate Library Portal</p></div><div style="padding: 35px 30px; background-color: #ffffff; color: #334155; line-height: 1.7;"><h3 style="color: #0F172A; margin-top: 0; font-size: 18px;">Request Rejected</h3><p>Hello {{EmployeeName}},</p><p>Unfortunately, your request to issue the book <strong>''{{BookName}}''</strong> has been rejected. The book may currently be unavailable or out of stock.</p><p style="margin-top: 30px;">Best Regards,<br><strong style="color: #0F172A;">Library Admin</strong></p></div><div style="background-color: #f8fafc; padding: 15px; text-align: center; font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0;">&copy; 2026 Jindal Stainless Limited. All rights reserved.</div></div>'
WHERE Purpose = 'Request Rejected';

IF NOT EXISTS (SELECT 1 FROM EmailTemplates WHERE Purpose = 'Issue Confirmation')
INSERT INTO EmailTemplates (Purpose, Subject, Body) VALUES ('Issue Confirmation', 'Book Issued: {{BookName}}', '');

UPDATE EmailTemplates SET Body = '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; box-shadow: 0 10px 25px rgba(0,0,0,0.05);"><div style="background-color: #0F172A; padding: 25px 20px; text-align: center; border-bottom: 4px solid #ea580c;"><h2 style="color: #ffffff; margin: 0; font-size: 22px; letter-spacing: 1px;">JINDAL STAINLESS</h2><p style="color: #ea580c; font-size: 11px; margin: 5px 0 0 0; text-transform: uppercase; letter-spacing: 2px; font-weight: bold;">Corporate Library Portal</p></div><div style="padding: 35px 30px; background-color: #ffffff; color: #334155; line-height: 1.7;"><h3 style="color: #0F172A; margin-top: 0; font-size: 18px;">Book Issued Successfully</h3><p>Hello {{EmployeeName}},</p><p>You have successfully issued the book <strong style="color: #ea580c;">''{{BookName}}''</strong>.</p><div style="background-color: #f8fafc; padding: 15px; border-left: 4px solid #ea580c; margin: 20px 0;"><strong style="color: #0F172A;">Due Date:</strong> {{DueDate}}</div><p style="margin-top: 30px;">Best Regards,<br><strong style="color: #0F172A;">Library Admin</strong></p></div><div style="background-color: #f8fafc; padding: 15px; text-align: center; font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0;">&copy; 2026 Jindal Stainless Limited. All rights reserved.</div></div>'
WHERE Purpose = 'Issue Confirmation';

IF NOT EXISTS (SELECT 1 FROM EmailTemplates WHERE Purpose = 'Overdue Reminder')
INSERT INTO EmailTemplates (Purpose, Subject, Body) VALUES ('Overdue Reminder', 'Reminder: Please return book ''{{BookName}}''', '');

UPDATE EmailTemplates SET Body = '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; box-shadow: 0 10px 25px rgba(0,0,0,0.05);"><div style="background-color: #0F172A; padding: 25px 20px; text-align: center; border-bottom: 4px solid #ea580c;"><h2 style="color: #ffffff; margin: 0; font-size: 22px; letter-spacing: 1px;">JINDAL STAINLESS</h2><p style="color: #ea580c; font-size: 11px; margin: 5px 0 0 0; text-transform: uppercase; letter-spacing: 2px; font-weight: bold;">Corporate Library Portal</p></div><div style="padding: 35px 30px; background-color: #ffffff; color: #334155; line-height: 1.7;"><h3 style="color: #e11d48; margin-top: 0; font-size: 18px;">Overdue Reminder</h3><p>Hello {{EmployeeName}},</p><p>This is a gentle reminder to please return the book <strong>''{{BookName}}''</strong>.</p><div style="background-color: #fff1f2; padding: 15px; border-left: 4px solid #e11d48; margin: 20px 0;"><strong style="color: #be123c;">Due Date Was:</strong> {{DueDate}}</div><p style="margin-top: 30px;">Thank You,<br><strong style="color: #0F172A;">Library Admin</strong></p></div><div style="background-color: #f8fafc; padding: 15px; text-align: center; font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0;">&copy; 2026 Jindal Stainless Limited. All rights reserved.</div></div>'
WHERE Purpose = 'Overdue Reminder';

IF NOT EXISTS (SELECT 1 FROM EmailTemplates WHERE Purpose = 'Login OTP')
INSERT INTO EmailTemplates (Purpose, Subject, Body) VALUES ('Login OTP', 'Your Library Login OTP: {{OTP}}', '');

UPDATE EmailTemplates SET Body = '<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 12px; overflow: hidden; box-shadow: 0 10px 25px rgba(0,0,0,0.05);"><div style="background-color: #0F172A; padding: 25px 20px; text-align: center; border-bottom: 4px solid #ea580c;"><h2 style="color: #ffffff; margin: 0; font-size: 22px; letter-spacing: 1px;">JINDAL STAINLESS</h2><p style="color: #ea580c; font-size: 11px; margin: 5px 0 0 0; text-transform: uppercase; letter-spacing: 2px; font-weight: bold;">Corporate Library Portal</p></div><div style="padding: 35px 30px; background-color: #ffffff; color: #334155; line-height: 1.7;"><h3 style="color: #0F172A; margin-top: 0; font-size: 18px;">Login Verification</h3><p>Hello {{EmployeeName}},</p><p>Your one-time password (OTP) for logging into the Library System is:</p><div style="margin: 25px 0; text-align: center;"><span style="display: inline-block; background-color: #f8fafc; border: 2px dashed #cbd5e1; padding: 15px 30px; font-size: 32px; font-weight: bold; letter-spacing: 5px; color: #ea580c; border-radius: 8px;">{{OTP}}</span></div><p style="font-size: 13px; color: #64748b; text-align: center;">This code is valid for 5 minutes.</p><p style="margin-top: 30px;">Best Regards,<br><strong style="color: #0F172A;">Library Admin</strong></p></div><div style="background-color: #f8fafc; padding: 15px; text-align: center; font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0;">&copy; 2026 Jindal Stainless Limited. All rights reserved.</div></div>'
WHERE Purpose = 'Login OTP';

GO
